language: python
python: 3.7
dist: xenial
sudo: true
matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
      sudo: true
      before_install:
        - pip install -r requirements.txt
    - os: windows
      language: sh
      python: "3.8"
      env: export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      before_install:
        - choco install python3
        - pip install -r requirements.txt
        - python setup.py install
script:
    - pytest
notifications:
  email:
    recipients:
      - jonathanvusich@gmail.com
    on_success: never
    on_failure: always